spring:
  application:
    name: ai-code-helper
  profiles:
    active: local  # local env

langchain4j:
  community:
    dashscope:
      chat-model:
        model-name: qwen-max
        api-key: <api key>
      embedding-model:
        model-name: text-embedding-v4
        api-key: <api key>

